export type MockSale = {
  id: string;
  date: string;
  branch: string;
  saleType: "POS" | "Courier" | "Diagnosing" | "Website";
  customerName: string;
  customerPhone: string;
  items: string;
  total: number;
  paymentStatus: "Paid" | "Due" | "Pending";
  dueAmount: number;
  status: "Completed" | "Pending" | "Cancelled" | "In Transit" | "Diagnosing" | "Returned";
  staff: string;
};

export const mockAllSales: MockSale[] = [
  {
    id: "SA001",
    date: "2024-03-15T10:30:00Z",
    branch: "Demo Portal",
    saleType: "POS",
    customerName: "Walk-in Customer",
    customerPhone: "N/A",
    items: "1x iPhone 15 Pro Max 256GB",
    total: 135000,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Completed",
    staff: "Rahim Ali",
  },
  {
    id: "SA002",
    date: "2024-03-15T11:15:00Z",
    branch: "Demo Bashundhara",
    saleType: "Courier",
    customerName: "Sumi Akter",
    customerPhone: "01811223344",
    items: "1x Samsung S21 Ultra Cover",
    total: 800,
    paymentStatus: "Due",
    dueAmount: 800,
    status: "In Transit",
    staff: "N/A",
  },
  {
    id: "SA003",
    date: "2024-03-16T09:45:00Z",
    branch: "Eastern Plaza",
    saleType: "Diagnosing",
    customerName: "Fahim Rahman",
    customerPhone: "01911223344",
    items: "1x MacBook Pro Keyboard Repair",
    total: 8500,
    paymentStatus: "Pending",
    dueAmount: 8500,
    status: "Diagnosing",
    staff: "N/A",
  },
  {
    id: "SA004",
    date: "2024-03-16T14:20:00Z",
    branch: "Gulistan Shopping Complex",
    saleType: "Website",
    customerName: "Mahmud Hasan",
    customerPhone: "01511223344",
    items: "1x AirPods Pro 2nd Gen",
    total: 25000,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Completed",
    staff: "N/A",
  },
  {
    id: "SA005",
    date: "2024-03-17T12:00:00Z",
    branch: "Motijheel Plaza",
    saleType: "POS",
    customerName: "Tariqul Islam",
    customerPhone: "01611223344",
    items: "1x Mi Power Bank 20000mAh",
    total: 1800,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Completed",
    staff: "Arif Hossain",
  },
  {
    id: "SA006",
    date: "2024-03-17T15:30:00Z",
    branch: "Demo Portal",
    saleType: "Diagnosing",
    customerName: "Nusrat Jahan",
    customerPhone: "01722334455",
    items: "1x OnePlus 9 Pro Motherboard Repair",
    total: 12000,
    paymentStatus: "Pending",
    dueAmount: 12000,
    status: "Diagnosing",
    staff: "Rahim Ali",
  },
  {
    id: "SA007",
    date: "2024-03-18T10:05:00Z",
    branch: "Eastern Plaza",
    saleType: "Website",
    customerName: "Kamrul Hasan",
    customerPhone: "01822334455",
    items: "1x iPad Air 5th Gen 64GB",
    total: 55000,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Pending",
    staff: "N/A",
  },
  {
    id: "SA008",
    date: "2024-03-18T13:40:00Z",
    branch: "Demo Bashundhara",
    saleType: "POS",
    customerName: "Walk-in Customer",
    customerPhone: "N/A",
    items: "1x 20W Fast Charger",
    total: 1500,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Completed",
    staff: "Karim Khan",
  },
  {
    id: "SA009",
    date: "2024-03-19T11:20:00Z",
    branch: "Gulistan Shopping Complex",
    saleType: "Courier",
    customerName: "Imran Khan",
    customerPhone: "01522334455",
    items: "1x Gaming Headset",
    total: 2800,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Delivered",
    staff: "N/A",
  },
  {
    id: "SA010",
    date: "2024-03-19T16:15:00Z",
    branch: "Motijheel Plaza",
    saleType: "Diagnosing",
    customerName: "Asif Akbar",
    customerPhone: "01622334455",
    items: "1x Apple Watch Series 6 Glass",
    total: 5500,
    paymentStatus: "Pending",
    dueAmount: 5500,
    status: "Cancelled",
    staff: "Arif Hossain",
  },
  {
    id: "SA011",
    date: "2024-03-20T09:10:00Z",
    branch: "Demo Portal",
    saleType: "Website",
    customerName: "Rubel Mia",
    customerPhone: "01733445566",
    items: "1x Samsung S24 Ultra",
    total: 125000,
    paymentStatus: "Due",
    dueAmount: 25000,
    status: "Pending",
    staff: "N/A",
  },
  {
    id: "SA012",
    date: "2024-03-20T14:50:00Z",
    branch: "Eastern Plaza",
    saleType: "Courier",
    customerName: "Sabina Yasmin",
    customerPhone: "01833445566",
    items: "1x Gimbal Stabilizer",
    total: 4500,
    paymentStatus: "Pending",
    dueAmount: 4500,
    status: "Returned",
    staff: "N/A",
  }
];
