export type MockService = {
  id: string;
  date: string;
  branch: string;
  customerName: string;
  customerPhone: string;
  device: string;
  technician: string;
  serviceCharge: number;
  paymentStatus: "Paid" | "Due" | "Pending";
  dueAmount: number;
  status: "Pending" | "In Progress" | "Ready for Pickup" | "Delivered" | "Cancelled";
};

export const mockServices: MockService[] = [
  {
    id: "SV001",
    date: "2024-03-15T10:30:00Z",
    branch: "Demo Portal",
    customerName: "Rashed Islam",
    customerPhone: "01711223344",
    device: "iPhone 13 Pro - Broken Display",
    technician: "Rahim Ali",
    serviceCharge: 15000,
    paymentStatus: "Due",
    dueAmount: 5000,
    status: "In Progress",
  },
  {
    id: "SV002",
    date: "2024-03-15T11:45:00Z",
    branch: "Demo Bashundhara",
    customerName: "Sumi Akter",
    customerPhone: "01811223344",
    device: "Samsung S21 - Battery Drain",
    technician: "Unassigned",
    serviceCharge: 2500,
    paymentStatus: "Pending",
    dueAmount: 2500,
    status: "Pending",
  },
  {
    id: "SV003",
    date: "2024-03-16T09:20:00Z",
    branch: "Eastern Plaza",
    customerName: "Fahim Rahman",
    customerPhone: "01911223344",
    device: "MacBook Pro M1 - Keyboard Issue",
    technician: "Kamal Hossain",
    serviceCharge: 8500,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Ready for Pickup",
  },
  {
    id: "SV004",
    date: "2024-03-16T14:10:00Z",
    branch: "Gulistan Shopping Complex",
    customerName: "Mahmud Hasan",
    customerPhone: "01511223344",
    device: "AirPods Pro - Right Earbud Not Working",
    technician: "Jamal Uddin",
    serviceCharge: 4500,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Delivered",
  },
  {
    id: "SV005",
    date: "2024-03-17T11:00:00Z",
    branch: "Motijheel Plaza",
    customerName: "Tariqul Islam",
    customerPhone: "01611223344",
    device: "iPad Air 4 - Screen Glass Replacement",
    technician: "Arif Hossain",
    serviceCharge: 6200,
    paymentStatus: "Due",
    dueAmount: 1200,
    status: "In Progress",
  },
  {
    id: "SV006",
    date: "2024-03-17T16:30:00Z",
    branch: "Demo Portal",
    customerName: "Nusrat Jahan",
    customerPhone: "01722334455",
    device: "OnePlus 9 Pro - Motherboard Dead",
    technician: "Rahim Ali",
    serviceCharge: 12000,
    paymentStatus: "Due",
    dueAmount: 12000,
    status: "Pending",
  },
  {
    id: "SV007",
    date: "2024-03-18T10:15:00Z",
    branch: "Eastern Plaza",
    customerName: "Kamrul Hasan",
    customerPhone: "01822334455",
    device: "Redmi Note 10 - Display Blank",
    technician: "Kamal Hossain",
    serviceCharge: 2800,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Ready for Pickup",
  },
  {
    id: "SV008",
    date: "2024-03-18T13:20:00Z",
    branch: "Demo Bashundhara",
    customerName: "Shabana Akter",
    customerPhone: "01922334455",
    device: "iPhone 13 Mini - Battery Swollen",
    technician: "Unassigned",
    serviceCharge: 4500,
    paymentStatus: "Pending",
    dueAmount: 4500,
    status: "Cancelled",
  },
  {
    id: "SV009",
    date: "2024-03-19T11:45:00Z",
    branch: "Gulistan Shopping Complex",
    customerName: "Imran Khan",
    customerPhone: "01522334455",
    device: "Poco X3 Pro - Power IC Issue",
    technician: "Jamal Uddin",
    serviceCharge: 3500,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Delivered",
  },
  {
    id: "SV010",
    date: "2024-03-19T15:10:00Z",
    branch: "Motijheel Plaza",
    customerName: "Asif Akbar",
    customerPhone: "01622334455",
    device: "Apple Watch Series 6 - Glass Broken",
    technician: "Arif Hossain",
    serviceCharge: 5500,
    paymentStatus: "Due",
    dueAmount: 1500,
    status: "In Progress",
  },
  {
    id: "SV011",
    date: "2024-03-20T09:30:00Z",
    branch: "Demo Portal",
    customerName: "Rubel Mia",
    customerPhone: "01733445566",
    device: "Samsung A52 - Charging Port Not Working",
    technician: "Rahim Ali",
    serviceCharge: 1200,
    paymentStatus: "Paid",
    dueAmount: 0,
    status: "Ready for Pickup",
  },
  {
    id: "SV012",
    date: "2024-03-20T14:45:00Z",
    branch: "Eastern Plaza",
    customerName: "Sabina Yasmin",
    customerPhone: "01833445566",
    device: "Vivo V20 - Green Line on Display",
    technician: "Kamal Hossain",
    serviceCharge: 3200,
    paymentStatus: "Pending",
    dueAmount: 3200,
    status: "Pending",
  }
];
